In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/work/assets/whoscored/euro2020/2021#italy.csv")

In [4]:
df

,Unnamed: 0,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,...,goalMouthZ,goalMouthY,isShot,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,venue,opponent
0,0,2.309967e+09,2,0,0.0,343,0.0,0.0,0,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy
1,1,2.309967e+09,2,0,0.0,338,0.0,0.0,0,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy
2,2,2.309967e+09,3,0,1.0,338,49.9,50.0,0,"[{'type': {'value': 140, 'displayName': 'PassE...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy
3,3,2.309967e+09,4,0,3.0,338,35.2,57.0,0,"[{'type': {'value': 1, 'displayName': 'Longbal...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy
4,4,2.309967e+09,5,0,7.0,338,73.0,3.4,0,"[{'type': {'value': 56, 'displayName': 'Zone'}...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2036,2036,2.309972e+09,837,126,36.0,343,0.0,0.0,130,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy
2037,2037,2.309972e+09,838,0,0.0,343,0.0,0.0,4,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy
2038,2038,2.309972e+09,1378,0,0.0,338,0.0,0.0,4,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy
2039,2039,2.309967e+09,1,0,0.0,343,0.0,0.0,0,"[{'type': {'value': 44, 'displayName': 'Player...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy
2040,2040,2.309967e+09,1,0,0.0,338,0.0,0.0,0,"[{'type': {'value': 130, 'displayName': 'TeamF...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wembley Stadium,Italy